### ISSUE TITLE
100% CPU usage when started

### ISSUE THREAD

**Issue by szotsaki** [sulix/keen-dreams-sdl2#3]
I started the game and it shows only a black screen while it eats 100% CPU.

Here is the backtrace:

```
#0  0x00007ffff6f387bd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff78c516d in ?? () from /usr/lib64/libGL.so.1
#2  0x00007ffff5751128 in ?? () from /usr/lib64/libnvidia-glcore.so.337.25
#3  0x00007ffff569473e in ?? () from /usr/lib64/libnvidia-glcore.so.337.25
#4  0x00007ffff78bc4c2 in ?? () from /usr/lib64/libGL.so.1
#5  0x00007ffff7895f1e in glXSwapBuffers () from /usr/lib64/libGL.so.1
#6  0x000000000041f86c in VW_GL_Present () at /home/aki/Programok/keen-dreams-sdl2/id_vw_gl.c:196
#7  0x00000000004124cb in IN_AckBack () at /home/aki/Programok/keen-dreams-sdl2/id_in.c:1055
#8  0x0000000000412584 in IN_Ack () at /home/aki/Programok/keen-dreams-sdl2/id_in.c:1083
#9  0x0000000000416d92 in US_FinishTextScreen () at /home/aki/Programok/keen-dreams-sdl2/id_us.c:530
#10 0x0000000000426f86 in InitGame () at /home/aki/Programok/keen-dreams-sdl2/kd_main.c:459
#11 0x00000000004270ed in main (argc=1, argv=0x7fffffffd2b8) at /home/aki/Programok/keen-dreams-sdl2/kd_main.c:514
```

And the full version:

```
#0  0x00007ffff6f387bd in poll () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x00007ffff78c516d in ?? () from /usr/lib64/libGL.so.1
No symbol table info available.
#2  0x00007ffff5751128 in ?? () from /usr/lib64/libnvidia-glcore.so.337.25
No symbol table info available.
#3  0x00007ffff569473e in ?? () from /usr/lib64/libnvidia-glcore.so.337.25
No symbol table info available.
#4  0x00007ffff78bc4c2 in ?? () from /usr/lib64/libGL.so.1
No symbol table info available.
#5  0x00007ffff7895f1e in glXSwapBuffers () from /usr/lib64/libGL.so.1
No symbol table info available.
#6  0x000000000041f86c in VW_GL_Present () at /home/aki/Programok/keen-dreams-sdl2/id_vw_gl.c:196
        offX = -nan(0x400000)
        endX = -nan(0x400000)
        vtxCoords = {-1, -1, 1, -1, 1, 1, -1, 1}
        texCoords = {-nan(0x400000), 1, -nan(0x400000), 1, -nan(0x400000), 0, -nan(0x400000), 0}
        vx = 0
        vy = 0
        vw = 1024
        vh = 768
#7  0x00000000004124cb in IN_AckBack () at /home/aki/Programok/keen-dreams-sdl2/id_in.c:1055
        evt = {type = 512, common = {type = 512, timestamp = 4376}, window = {type = 512, timestamp = 4376, windowID = 2, event = 11 '\v', padding1 = 127 '\177', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 0, data2 = 0}, key = {type = 512, timestamp = 4376, windowID = 2, state = 11 '\v', repeat = 127 '\177', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {scancode = SDL_SCANCODE_UNKNOWN, sym = 0, mod = 2, unused = 0}}, edit = {type = 512, timestamp = 4376, windowID = 2, text = "\v\177\000\000\000\000\000\000\000\000\000\000\002", '\000' <repeats 11 times>, "h\001\000\000C\001\000", start = 0, length = -21}, text = {type = 512, timestamp = 4376, windowID = 2, text = "\v\177\000\000\000\000\000\000\000\000\000\000\002", '\000' <repeats 11 times>, "h\001\000\000C\001\000"}, motion = {type = 512, timestamp = 4376, windowID = 2, which = 32523, state = 0, x = 0, y = 2, xrel = 0, yrel = 0}, button = {type = 512, timestamp = 4376, windowID = 2, which = 32523, button = 0 '\000', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 0, y = 2}, wheel = {type = 512, timestamp = 4376, windowID = 2, which = 32523, x = 0, y = 0}, jaxis = {type = 512, timestamp = 4376, which = 2, axis = 11 '\v', padding1 = 127 '\177', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, jball = {type = 512, timestamp = 4376, which = 2, ball = 11 '\v', padding1 = 127 '\177', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 0, yrel = 0}, jhat = {type = 512, timestamp = 4376, which = 2, hat = 11 '\v', value = 127 '\177', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 512, timestamp = 4376, which = 2, button = 11 '\v', state = 127 '\177', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 512, timestamp = 4376, which = 2}, caxis = {type = 512, timestamp = 4376, which = 2, axis = 11 '\v', padding1 = 127 '\177', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, cbutton = {type = 512, timestamp = 4376, which = 2, button = 11 '\v', state = 127 '\177', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 512, timestamp = 4376, which = 2}, quit = {type = 512, timestamp = 4376}, user = {type = 512, timestamp = 4376, windowID = 2, code = 32523, data1 = 0x0, data2 = 0x2}, syswm = {type = 512, timestamp = 4376, msg = 0x7f0b00000002}, tfinger = {type = 512, timestamp = 4376, touchId = 139685221367810, fingerId = 0, x = 2.80259693e-45, y = 0, dx = 0, dy = 5.04467447e-43, pressure = 4.52619404e-43}, mgesture = {type = 512, timestamp = 4376, touchId = 139685221367810, dTheta = 0, dDist = 0, x = 2.80259693e-45, y = 0, numFingers = 0, padding = 0}, dgesture = {type = 512, timestamp = 4376, touchId = 139685221367810, gestureId = 0, numFingers = 2, error = 0, x = 0, y = 5.04467447e-43}, drop = {type = 512, timestamp = 4376, file = 0x7f0b00000002 <Address 0x7f0b00000002 out of bounds>}, padding = "\000\002\000\000\030\021\000\000\002\000\000\000\v\177\000\000\000\000\000\000\000\000\000\000\002", '\000' <repeats 11 times>, "h\001\000\000C\001\000\000\000\000\000\000\353\377\377\377\000\000\000"}
        i = 2
#8  0x0000000000412584 in IN_Ack () at /home/aki/Programok/keen-dreams-sdl2/id_in.c:1083
        i = 2
#9  0x0000000000416d92 in US_FinishTextScreen () at /home/aki/Programok/keen-dreams-sdl2/id_us.c:530
No locals.
#10 0x0000000000426f86 in InitGame () at /home/aki/Programok/keen-dreams-sdl2/kd_main.c:459
        i = 213
#11 0x00000000004270ed in main (argc=1, argv=0x7fffffffd2b8) at /home/aki/Programok/keen-dreams-sdl2/kd_main.c:514
No locals.
```

I just copied the content of the shareware KEENDR13.ZIP into the static lib and run the KDreams from there.

OS: openSUSE 12.3, x64.

**Comment by sulix** [comment]
Keen should just have been waiting for a keypress there: the original game had a B8000 text screen there ("Ready - Press a Key") which the SDL2 version doesn't.

I've removed that now, so it should boot straight to the title screen.

You'll need to make sure that you're using the static/ files from the Keen Dreams 1.13 commit here: https://github.com/keendreams/keen/tree/a7591c4af15c479d8d1c0be5ce1d49940554157c/static as well. The ones in the latest commit come from version 1.92/1.93.

**Comment by szotsaki** [comment]
Thank you, this commit fixed this issue and after checking out the static files you linked, the game started as well.
